package com.cqvip.mobilevers.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cqvip.mobilevers.db.OneLevelType;
import com.cqvip.mobilevers.db.TwoLevelType;
import com.cqvip.mobilevers.db.ThreeLevelType;
import com.cqvip.mobilevers.db.FourLevelType;

import com.cqvip.mobilevers.db.OneLevelTypeDao;
import com.cqvip.mobilevers.db.TwoLevelTypeDao;
import com.cqvip.mobilevers.db.ThreeLevelTypeDao;
import com.cqvip.mobilevers.db.FourLevelTypeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig oneLevelTypeDaoConfig;
    private final DaoConfig twoLevelTypeDaoConfig;
    private final DaoConfig threeLevelTypeDaoConfig;
    private final DaoConfig fourLevelTypeDaoConfig;

    private final OneLevelTypeDao oneLevelTypeDao;
    private final TwoLevelTypeDao twoLevelTypeDao;
    private final ThreeLevelTypeDao threeLevelTypeDao;
    private final FourLevelTypeDao fourLevelTypeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        oneLevelTypeDaoConfig = daoConfigMap.get(OneLevelTypeDao.class).clone();
        oneLevelTypeDaoConfig.initIdentityScope(type);

        twoLevelTypeDaoConfig = daoConfigMap.get(TwoLevelTypeDao.class).clone();
        twoLevelTypeDaoConfig.initIdentityScope(type);

        threeLevelTypeDaoConfig = daoConfigMap.get(ThreeLevelTypeDao.class).clone();
        threeLevelTypeDaoConfig.initIdentityScope(type);

        fourLevelTypeDaoConfig = daoConfigMap.get(FourLevelTypeDao.class).clone();
        fourLevelTypeDaoConfig.initIdentityScope(type);

        oneLevelTypeDao = new OneLevelTypeDao(oneLevelTypeDaoConfig, this);
        twoLevelTypeDao = new TwoLevelTypeDao(twoLevelTypeDaoConfig, this);
        threeLevelTypeDao = new ThreeLevelTypeDao(threeLevelTypeDaoConfig, this);
        fourLevelTypeDao = new FourLevelTypeDao(fourLevelTypeDaoConfig, this);

        registerDao(OneLevelType.class, oneLevelTypeDao);
        registerDao(TwoLevelType.class, twoLevelTypeDao);
        registerDao(ThreeLevelType.class, threeLevelTypeDao);
        registerDao(FourLevelType.class, fourLevelTypeDao);
    }
    
    public void clear() {
        oneLevelTypeDaoConfig.getIdentityScope().clear();
        twoLevelTypeDaoConfig.getIdentityScope().clear();
        threeLevelTypeDaoConfig.getIdentityScope().clear();
        fourLevelTypeDaoConfig.getIdentityScope().clear();
    }

    public OneLevelTypeDao getOneLevelTypeDao() {
        return oneLevelTypeDao;
    }

    public TwoLevelTypeDao getTwoLevelTypeDao() {
        return twoLevelTypeDao;
    }

    public ThreeLevelTypeDao getThreeLevelTypeDao() {
        return threeLevelTypeDao;
    }

    public FourLevelTypeDao getFourLevelTypeDao() {
        return fourLevelTypeDao;
    }

}
