package com.cqvip.mobilevers.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.ArrayList;
import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;
// KEEP INCLUDES END
/**
 * Entity mapped to table ONE_LEVEL_TYPE.
 */
public class OneLevelType {

    private Long id;
    private Integer examtypeid;
    private Integer count;
    private String title;
    private Boolean haschildren;

    // KEEP FIELDS - put your custom fields here
    //int testint;
    // KEEP FIELDS END

    public OneLevelType() {
    }

    public OneLevelType(Long id) {
        this.id = id;
    }

    public OneLevelType(Long id, Integer examtypeid, Integer count, String title, Boolean haschildren) {
        this.id = id;
        this.examtypeid = examtypeid;
        this.count = count;
        this.title = title;
        this.haschildren = haschildren;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getExamtypeid() {
        return examtypeid;
    }

    public void setExamtypeid(Integer examtypeid) {
        this.examtypeid = examtypeid;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Boolean getHaschildren() {
        return haschildren;
    }

    public void setHaschildren(Boolean haschildren) {
        this.haschildren = haschildren;
    }

    // KEEP METHODS - put your custom methods here
	@Override
	public String toString() {
		return "OneLevelType [id=" + id + ", examtypeid=" + examtypeid
				+ ", count=" + count + ", title=" + title + ", haschildren="
				+ haschildren + "]";
	}
    
	public static List<OneLevelType> parserJsonData(String data){
		List<OneLevelType> mtempList=new ArrayList<OneLevelType>();
		try{
			JSONObject js = new JSONObject(data);
			JSONArray arrayList= js.getJSONArray("categorys");
			for(int i=0;i<arrayList.length();i++){
				JSONObject obj=arrayList.getJSONObject(i);
				OneLevelType detail=new OneLevelType();
				detail.setExamtypeid(Integer.parseInt(obj.getString("id")));
				detail.setTitle(obj.getString("title"));
				detail.setCount(Integer.parseInt(obj.getString("count")));
				detail.setHaschildren(obj.getBoolean("haschildren"));
				mtempList.add(detail);
			}
			//System.out.println(mtempList.size());
			//System.out.println(mtempList.toString());
			return mtempList;
		}catch(Exception e){
			e.printStackTrace();
		}
		return null;
	}
    // KEEP METHODS END

}
