package com.cqvip.mobilevers.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.ArrayList;
import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;
// KEEP INCLUDES END
/**
 * Entity mapped to table TWO_LEVEL_TYPE.
 */
public class TwoLevelType {

    private Long id;
    private Integer superiorexamtypeid;
    private Integer examtypeid;
    private Integer count;
    private String title;
    private Boolean haschildren;
    private Boolean isprivate;
    private Integer level;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TwoLevelType() {
    }

    public TwoLevelType(Long id) {
        this.id = id;
    }

    public TwoLevelType(Long id, Integer superiorexamtypeid, Integer examtypeid, Integer count, String title, Boolean haschildren, Boolean isprivate, Integer level) {
        this.id = id;
        this.superiorexamtypeid = superiorexamtypeid;
        this.examtypeid = examtypeid;
        this.count = count;
        this.title = title;
        this.haschildren = haschildren;
        this.isprivate = isprivate;
        this.level = level;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSuperiorexamtypeid() {
        return superiorexamtypeid;
    }

    public void setSuperiorexamtypeid(Integer superiorexamtypeid) {
        this.superiorexamtypeid = superiorexamtypeid;
    }

    public Integer getExamtypeid() {
        return examtypeid;
    }

    public void setExamtypeid(Integer examtypeid) {
        this.examtypeid = examtypeid;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Boolean getHaschildren() {
        return haschildren;
    }

    public void setHaschildren(Boolean haschildren) {
        this.haschildren = haschildren;
    }

    public Boolean getIsprivate() {
        return isprivate;
    }

    public void setIsprivate(Boolean isprivate) {
        this.isprivate = isprivate;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    // KEEP METHODS - put your custom methods here
	public static List<TwoLevelType> parserJsonData(String data,int level,String superiorexamtypeid,boolean isprivate){
		List<TwoLevelType> mtempList=new ArrayList<TwoLevelType>();
		try{
			JSONObject js = new JSONObject(data);
			JSONArray arrayList= js.getJSONArray("categorys");
			for(int i=0;i<arrayList.length();i++){
				JSONObject obj=arrayList.getJSONObject(i);
				TwoLevelType detail=new TwoLevelType();
				detail.setSuperiorexamtypeid(Integer.parseInt(superiorexamtypeid));
				detail.setExamtypeid(Integer.parseInt(obj.getString("id")));
				detail.setTitle(obj.getString("title"));
				detail.setCount(Integer.parseInt(obj.getString("count")));
				detail.setHaschildren(obj.getBoolean("haschildren"));
				detail.setIsprivate(isprivate);
				detail.setLevel(level);
				mtempList.add(detail);
			}
			//System.out.println(mtempList.size());
			//System.out.println(mtempList.toString());
			return mtempList;
		}catch(Exception e){
			e.printStackTrace();
		}
		return null;
	}
	
    @Override
	public String toString() {
		return "TwoLevelType [id=" + id + ", superiorexamtypeid="
				+ superiorexamtypeid + ", examtypeid=" + examtypeid
				+ ", count=" + count + ", title=" + title + ", haschildren="
				+ haschildren + ", isprivate=" + isprivate + ", level=" + level
				+ "]";
	}
    // KEEP METHODS END

}
