package com.cqvip.mobilevers.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.cqvip.mobilevers.db.TwoLevelType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TWO_LEVEL_TYPE.
*/
public class TwoLevelTypeDao extends AbstractDao<TwoLevelType, Long> {

    public static final String TABLENAME = "TWO_LEVEL_TYPE";

    /**
     * Properties of entity TwoLevelType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Superiorexamtypeid = new Property(1, Integer.class, "superiorexamtypeid", false, "SUPERIOREXAMTYPEID");
        public final static Property Examtypeid = new Property(2, Integer.class, "examtypeid", false, "EXAMTYPEID");
        public final static Property Count = new Property(3, Integer.class, "count", false, "COUNT");
        public final static Property Title = new Property(4, String.class, "title", false, "TITLE");
        public final static Property Haschildren = new Property(5, Boolean.class, "haschildren", false, "HASCHILDREN");
        public final static Property Isprivate = new Property(6, Boolean.class, "isprivate", false, "ISPRIVATE");
    };


    public TwoLevelTypeDao(DaoConfig config) {
        super(config);
    }
    
    public TwoLevelTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TWO_LEVEL_TYPE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SUPERIOREXAMTYPEID' INTEGER UNIQUE ," + // 1: superiorexamtypeid
                "'EXAMTYPEID' INTEGER UNIQUE ," + // 2: examtypeid
                "'COUNT' INTEGER," + // 3: count
                "'TITLE' TEXT," + // 4: title
                "'HASCHILDREN' INTEGER," + // 5: haschildren
                "'ISPRIVATE' INTEGER);"); // 6: isprivate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TWO_LEVEL_TYPE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TwoLevelType entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer superiorexamtypeid = entity.getSuperiorexamtypeid();
        if (superiorexamtypeid != null) {
            stmt.bindLong(2, superiorexamtypeid);
        }
 
        Integer examtypeid = entity.getExamtypeid();
        if (examtypeid != null) {
            stmt.bindLong(3, examtypeid);
        }
 
        Integer count = entity.getCount();
        if (count != null) {
            stmt.bindLong(4, count);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
 
        Boolean haschildren = entity.getHaschildren();
        if (haschildren != null) {
            stmt.bindLong(6, haschildren ? 1l: 0l);
        }
 
        Boolean isprivate = entity.getIsprivate();
        if (isprivate != null) {
            stmt.bindLong(7, isprivate ? 1l: 0l);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TwoLevelType readEntity(Cursor cursor, int offset) {
        TwoLevelType entity = new TwoLevelType( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // superiorexamtypeid
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // examtypeid
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // count
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // title
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // haschildren
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0 // isprivate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TwoLevelType entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSuperiorexamtypeid(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setExamtypeid(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setCount(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setTitle(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setHaschildren(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setIsprivate(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TwoLevelType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TwoLevelType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
