package com.cqvip.mobilevers.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TWO_LEVEL_TYPE.
 */
public class TwoLevelType {

    private Long id;
    private Integer superiorexamtypeid;
    private Integer examtypeid;
    private Integer count;
    private String title;
    private Boolean haschildren;
    private Boolean isprivate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TwoLevelType() {
    }

    public TwoLevelType(Long id) {
        this.id = id;
    }

    public TwoLevelType(Long id, Integer superiorexamtypeid, Integer examtypeid, Integer count, String title, Boolean haschildren, Boolean isprivate) {
        this.id = id;
        this.superiorexamtypeid = superiorexamtypeid;
        this.examtypeid = examtypeid;
        this.count = count;
        this.title = title;
        this.haschildren = haschildren;
        this.isprivate = isprivate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSuperiorexamtypeid() {
        return superiorexamtypeid;
    }

    public void setSuperiorexamtypeid(Integer superiorexamtypeid) {
        this.superiorexamtypeid = superiorexamtypeid;
    }

    public Integer getExamtypeid() {
        return examtypeid;
    }

    public void setExamtypeid(Integer examtypeid) {
        this.examtypeid = examtypeid;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Boolean getHaschildren() {
        return haschildren;
    }

    public void setHaschildren(Boolean haschildren) {
        this.haschildren = haschildren;
    }

    public Boolean getIsprivate() {
        return isprivate;
    }

    public void setIsprivate(Boolean isprivate) {
        this.isprivate = isprivate;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
