package com.cqvip.mobilevers.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.ArrayList;
import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;
// KEEP INCLUDES END
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    private String userid;
    private String name;
    private String realname;
    private Integer testingcount;
    private Integer testedcount;
    private Integer favoritescount;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String userid, String name, String realname, Integer testingcount, Integer testedcount, Integer favoritescount) {
        this.id = id;
        this.userid = userid;
        this.name = name;
        this.realname = realname;
        this.testingcount = testingcount;
        this.testedcount = testedcount;
        this.favoritescount = favoritescount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRealname() {
        return realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }

    public Integer getTestingcount() {
        return testingcount;
    }

    public void setTestingcount(Integer testingcount) {
        this.testingcount = testingcount;
    }

    public Integer getTestedcount() {
        return testedcount;
    }

    public void setTestedcount(Integer testedcount) {
        this.testedcount = testedcount;
    }

    public Integer getFavoritescount() {
        return favoritescount;
    }

    public void setFavoritescount(Integer favoritescount) {
        this.favoritescount = favoritescount;
    }

    // KEEP METHODS - put your custom methods here
	public static User parserJsonData(String data){
		User user=new User();
		try{
			JSONObject js = new JSONObject(data);
			JSONObject userinfo= js.getJSONObject("userinfo");
			user.setUserid(userinfo.getString("userid").trim());
			user.setName(userinfo.getString("name").trim());
			user.setRealname(userinfo.getString("realname").trim());
			user.setTestingcount(userinfo.getInt("testingcount"));
			user.setTestedcount(userinfo.getInt("testedcount"));
			user.setFavoritescount(userinfo.getInt("favoritescount"));
			return user;
		}catch(Exception e){
			e.printStackTrace();
		}
		return null;
	}
    // KEEP METHODS END

}
