package com.cqvip.mobilevers.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.ArrayList;
import java.util.List;

import org.json.JSONArray;
import org.json.JSONObject;
// KEEP INCLUDES END
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    private String userid;
    private String username;
    private String realname;
    private Integer testscorecount;
    private Integer favoritescount;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String userid, String username, String realname, Integer testscorecount, Integer favoritescount) {
        this.id = id;
        this.userid = userid;
        this.username = username;
        this.realname = realname;
        this.testscorecount = testscorecount;
        this.favoritescount = favoritescount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getRealname() {
        return realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }

    public Integer getTestscorecount() {
        return testscorecount;
    }

    public void setTestscorecount(Integer testscorecount) {
        this.testscorecount = testscorecount;
    }

    public Integer getFavoritescount() {
        return favoritescount;
    }

    public void setFavoritescount(Integer favoritescount) {
        this.favoritescount = favoritescount;
    }

    // KEEP METHODS - put your custom methods here
	public static User parserJsonData(String data){
		User user=new User();
		try{
			JSONObject js = new JSONObject(data);
			JSONObject userinfo= js.getJSONObject("userinfo");
			user.setUserid(userinfo.getString("userid").trim());
			user.setUsername(userinfo.getString("name").trim());
			user.setRealname(userinfo.getString("realname").trim());
			user.setTestscorecount(userinfo.getInt("testscorecount"));
			user.setFavoritescount(userinfo.getInt("favoritescount"));
			return user;
		}catch(Exception e){
			e.printStackTrace();
		}
		return null;
	}
    // KEEP METHODS END

}
